spring:
  datasource:
    url: jdbc:postgresql://guest-db:5432/guestdb
    username: guestuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: guest
    show-sql: true
  flyway:
    enabled: true
    schemas: guest
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: 8080